name: C++ Doctest CI

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y g++ cmake make

      - name: Configure CMake
        run: |
          mkdir build
          cd build
          cmake ..
      
      - name: Compile all tests
        run: |
          cd build
          make

      - name: Run each test separately
        run: |
          for test in build/*; do
            if [[ -x "$test" && "$test" != *".o" && "$test" != *"CMakeFiles"* ]]; then
              echo "Running test: $test"
              $test
            fi
          done
